M48
; DRILL file {KiCad 9.0.0} date 2025-06-20T07:10:22-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-20T07:10:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0945
%
G90
G05
T1
X2.628Y-3.4945
T2
X4.2768Y-3.3972
X4.7811Y-3.3972
M30
